templateDir: ./sdk-resources/resources
packageName: sailpoint.beta
packageVersion: 1.4.1
apiVersion: beta
generateSourceCodeOnly: true
functionPrefix: Beta
subModuleName: Beta
files:
  developerSite_code_examples.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/beta/docs/Examples/python_code_examples_overlay.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/beta/docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/beta/Index.md
