templateDir: ./sdk-resources/resources
packageName: sailpoint.v3
packageVersion: 1.2.8
apiVersion: v3
generateSourceCodeOnly: true
funtionPrefix:
subModuleName: V3
files:
  developerSite_code_examples.mustache:
    templateType: APIDocs
    destinationFilename: developerSite_code_examples.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v3/docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v3/Index.md
