templateDir: ./sdk-resources/resources
packageName: sailpoint.v3
packageVersion: 1.4.0
apiVersion: v3
generateSourceCodeOnly: true
functionPrefix:
subModuleName: V3
files:
  developerSite_code_examples.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v3/docs/Examples/python_code_examples_overlay.yaml
  docs_methods_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v3/docs/Methods/Index.md
  docs_models_index.mustache:
    templateType: SupportingFiles
    destinationFilename: sailpoint/v3/Index.md
